# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audioqna-backend-server-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioqna-backend-server-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      labels:
        app: audioqna-backend-server-deploy
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: audioqna-backend-server-deploy
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: audio-qna-config
        image: opea/audioqna:latest
        imagePullPolicy: IfNotPresent
        name: audioqna-backend-server-deploy
        args: null
        ports:
        - containerPort: 8888
      serviceAccountName: default
---
kind: Service
apiVersion: v1
metadata:
  name: audioqna-backend-server-svc
spec:
  type: NodePort
  selector:
    app: audioqna-backend-server-deploy
  ports:
  - name: service
    port: 3008
    targetPort: 8888
    nodePort: 30888
